spring:
    datasource:
        url: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/sejhfrus
        username: sejhfrus
        password: tK-S3zbTefc1JF9dRFuRPzFUUJel_jse
        driver-class-name: org.postgresql.Driver
        platform: postgres
        max-idle: 0
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        org.springframework.web: INFO
        org.hibernate: ERROR
        net.guides: DEBUG
